### PR TITLE
Default to the "en" locale when the system locale is not supported

### PR DESCRIPTION
**Pull request by broodroosterdev**
Instead of defaulting to null and crashing the app, the locale will now be defaulted to the "en" locale.

### CODE REVIEW

**Comment by dvd-bnc** [comment]
This approach makes the app not follow the system locale, you should handle the error and use en just in that case, this approach isn't to the one to use

**Comment by broodroosterdev** [comment]
notes_main_page_route.dart:272
```
@override
  Widget build(BuildContext context) {
    appInfo = Provider.of<AppInfoProvider>(context);
    locales = AppLocalizations.of(context);
    if(AppLocalizations.of(context) == null){
//Print to log
//Change to EN locale     
}
```
Would this be more like what you want?

**Comment by dvd-bnc** [comment]
the problem here isn't the locale being null, it's about the fact that there are no localization providers that support the system locale. a better approach would be to try adding current locale to the array of supported locales in main

**Review by dvd-bnc — COMMENTED** [review]
the boolean logic in there doesnt seem to be working because while toString returns xx_YY, the split method returns only xx so they'll never be the same. Also, did you test the return Locale("en") behaviour?

**Comment by broodroosterdev** [comment]
`print(supportedLocale.toString()); // de`
`print(locale.toString()); // nl_NL`
This is what both Locales return. It surprised me too when i first saw it. I did test the return Locale("en) and when i switched from a supported locale(de) to my system locale(nl) the interface was in english.

**Comment by dvd-bnc** [comment]
hm, ill try your commit and report

**Comment by broodroosterdev** [comment]
```Dart
if (locale.languageCode == supportedLocale.languageCode) {
                return supportedLocale;
 }
```
Comparing the languageCode of both the locales seems to be the safest way of comparing. I also changed the log message to be: "The (locale) locale is not supported".

**Comment by dvd-bnc** [comment]
You tested this change and it's working as expected? If yes, I'll probably merge

**Comment by broodroosterdev** [comment]
I just tested this change by opening the app with the German system locale set. It will display the intl_de.arb strings. I then changed the system locale to Dutch, and it displayed the strings from the intl_en.arb file. I dont see any potential bugs or problems with this approach so it is working as expected and ready to be merged! I would recommend to squash the commits and then merge since the previous 2 commits aren't worth keeping in the git history.

**Comment by dvd-bnc** [comment]
this works, even quite well actually, merging

**Pull request merged**
